// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.304000,HLS_SYN_LAT=43,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=112,HLS_SYN_LUT=264,HLS_VERSION=2023_1}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r,
        out_r,
        out_r_ap_vld,
        shift_reg_address0,
        shift_reg_ce0,
        shift_reg_we0,
        shift_reg_d0,
        shift_reg_q0,
        shift_reg_address1,
        shift_reg_ce1,
        shift_reg_q1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_r;
output  [9:0] out_r;
output   out_r_ap_vld;
output  [3:0] shift_reg_address0;
output   shift_reg_ce0;
output   shift_reg_we0;
output  [7:0] shift_reg_d0;
input  [7:0] shift_reg_q0;
output  [3:0] shift_reg_address1;
output   shift_reg_ce1;
input  [7:0] shift_reg_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ap_vld;
reg[3:0] shift_reg_address0;
reg shift_reg_ce0;
reg shift_reg_we0;
reg[7:0] shift_reg_d0;
reg shift_reg_ce1;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_done;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_idle;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_ready;
wire   [3:0] grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address0;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce0;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_we0;
wire   [7:0] grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_d0;
wire   [3:0] grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address1;
wire    grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce1;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_ap_done;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_ap_idle;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_ap_ready;
wire   [3:0] grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_address0;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_ce0;
wire   [9:0] grp_fir_Pipeline_ACC_LOOP_fu_76_acc_out;
wire    grp_fir_Pipeline_ACC_LOOP_fu_76_acc_out_ap_vld;
reg    grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg = 1'b0;
#0 grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg = 1'b0;
end

fir_fir_Pipeline_SHIFT_LOOP grp_fir_Pipeline_SHIFT_LOOP_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start),
    .ap_done(grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_done),
    .ap_idle(grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_idle),
    .ap_ready(grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_ready),
    .shift_reg_address0(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address0),
    .shift_reg_ce0(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce0),
    .shift_reg_we0(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_we0),
    .shift_reg_d0(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_d0),
    .shift_reg_address1(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address1),
    .shift_reg_ce1(grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce1),
    .shift_reg_q1(shift_reg_q1)
);

fir_fir_Pipeline_ACC_LOOP grp_fir_Pipeline_ACC_LOOP_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start),
    .ap_done(grp_fir_Pipeline_ACC_LOOP_fu_76_ap_done),
    .ap_idle(grp_fir_Pipeline_ACC_LOOP_fu_76_ap_idle),
    .ap_ready(grp_fir_Pipeline_ACC_LOOP_fu_76_ap_ready),
    .shift_reg_address0(grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_address0),
    .shift_reg_ce0(grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_ce0),
    .shift_reg_q0(shift_reg_q0),
    .acc_out(grp_fir_Pipeline_ACC_LOOP_fu_76_acc_out),
    .acc_out_ap_vld(grp_fir_Pipeline_ACC_LOOP_fu_76_acc_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_ACC_LOOP_fu_76_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_Pipeline_ACC_LOOP_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_address0 = grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_address0 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address0;
    end else begin
        shift_reg_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_ce0 = grp_fir_Pipeline_ACC_LOOP_fu_76_shift_reg_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_ce0 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce0;
    end else begin
        shift_reg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_ce1 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_ce1;
    end else begin
        shift_reg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_d0 = in_r;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_d0 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_d0;
    end else begin
        shift_reg_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        shift_reg_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_we0 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_we0;
    end else begin
        shift_reg_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fir_Pipeline_ACC_LOOP_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start = grp_fir_Pipeline_ACC_LOOP_fu_76_ap_start_reg;

assign grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start = grp_fir_Pipeline_SHIFT_LOOP_fu_70_ap_start_reg;

assign out_r = grp_fir_Pipeline_ACC_LOOP_fu_76_acc_out;

assign shift_reg_address1 = grp_fir_Pipeline_SHIFT_LOOP_fu_70_shift_reg_address1;

endmodule //fir
